# This workflow will help you to produce newman test run

name: Newman Tests
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
   # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
    
      # Install newman globally, the reporter for slack and install the html extra reporter
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-slackreporter
        
   # Run the POSTMAN collection
      - name: Run API Tests
        run: newman run https://api.getpostman.com/collections/12559118-c097f106-044b-4b9c-9c27-0bd4658f5804?apikey=PMAK-62f1fd2a56d9256ffcb56f73-3c12b6b28917f1471d973d773179de9e47 -r slackreporter --reporter-slackreporter-webhookurl https://hooks.slack.com/services/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
